### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by taniki** [amineabdaoui/python-heideltime#5]
## Environnement

- MacOS Big Sur

## Output

```
english
Sept 09, 2021 11:50:31 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone initialize
INFO: HeidelTimeStandalone initialized with language english
Sept 09, 2021 11:50:31 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone readConfigFile
INFO: trying to read in file config.props
Sept 09, 2021 11:50:33 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone initialize
INFO: HeidelTime initialized
Sept 09, 2021 11:50:33 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone initialize
INFO: JCas factory initialized
Sept 09, 2021 11:50:33 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone process
INFO: Processing started
java.io.IOException: Cannot run program "TreeTagger/bin/tree-tagger": error=86, Bad CPU type in executable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at de.unihd.dbs.uima.annotator.treetagger.TreeTaggerProperties.getTreeTaggingProcess(TreeTaggerProperties.java:159)
        at de.unihd.dbs.uima.annotator.treetagger.TreeTaggerWrapper.doTreeTag(TreeTaggerWrapper.java:372)
        at de.unihd.dbs.uima.annotator.treetagger.TreeTaggerWrapper.process(TreeTaggerWrapper.java:242)
        at de.unihd.dbs.heideltime.standalone.components.impl.TreeTaggerWrapper.process(TreeTaggerWrapper.java:43)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishPartOfSpeechInformation(HeidelTimeStandalone.java:422)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishHeidelTimePreconditions(HeidelTimeStandalone.java:332)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:516)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:465)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
        ... 9 more
java.lang.NullPointerException: Cannot invoke "de.unihd.dbs.uima.annotator.treetagger.TreeTaggerProcess.close()" because "this.ttProc" is null
        at de.unihd.dbs.uima.annotator.treetagger.TreeTaggerWrapper.quit(TreeTaggerWrapper.java:710)
        at de.unihd.dbs.heideltime.standalone.components.impl.TreeTaggerWrapper.reset(TreeTaggerWrapper.java:64)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishPartOfSpeechInformation(HeidelTimeStandalone.java:423)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishHeidelTimePreconditions(HeidelTimeStandalone.java:332)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:516)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:465)
Sept 09, 2021 11:50:33 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone process
WARNING: Processing aborted due to errors
Sept 09, 2021 11:50:33 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone process
INFO: Result formatted
```

**Comment by amineabdaoui** [comment]
Hi, 

Sorry for my late reply. 
I didn't receive email notifications about this repo and I was not checking it recently. 

The pre-installed version of TreeTagger that I included here is not able to run on your CPU. 
I suggest you download the appropriate TreeTagger files and re-run the installation scripts on your machine. Just follow the instructions in: https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/

Amine
